### PR TITLE
feat: add start/end Points, Typescript definitions, standardize plugin handler names

### LINKED ISSUE #41: `Could not find a declaration file for module 'leaflet-area-select'.`
Add a new declaration (.d.ts) file containing `declare module 'leaflet-area-select';`

I might do this for ya.

### LINKED ISSUE #42: Expose start/end coordinates
I am curious if you expose the start and end coordinates that have been clicked, this is a requirement of my use case.

Thank you!

### PR DESCRIPTION
**Pull request by charlieforward9**
Fix #41
Fix #42

### CODE REVIEW

**Comment by charlieforward9** [comment]
<s>I am having some trouble augmenting the Leaflet types within my own project after defining the extensions in this package. When I `declare module...` in my code, it works correctly, just prefer to augment within the package that defines the logic.</s>

**Comment by charlieforward9** [comment]
`"leaflet"` module augmentation working as expected on my end!

**Comment by charlieforward9** [comment]
@w8r please review this when you have a chance. I would like to clean up our package json to depend on npm packages rather than git.

**Comment by w8r** [comment]
Impeccable!

**Comment by w8r** [comment]
Released

**Pull request merged**
